image:
  name: alpine/helm:3.2.1
  entrypoint: ["/bin/sh", "-c"]

variables:
  HELM_EXPERIMENTAL_OCI: 1
  CHART_NAME: varnish
  CHART_PROGECT: tebaly/varnish-chart
  CHART_REGISTRY_URL: $CI_REGISTRY/$CHART_PROGECT/$CHART_NAME:$CI_COMMIT_TAG

stages:
  - build
build:
  stage: build
  script:
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - helm chart save ./ $CHART_REGISTRY_URL
    - helm chart push $CHART_REGISTRY_URL
  only:
    - tags


