image:
  name: alpine/helm:3.2.1
  entrypoint: ["/bin/sh", "-c"]

variables:
  HELM_EXPERIMENTAL_OCI: 1
  CHART_NAME: varnish
  CHART_PATH: helm/$CHART_NAME
  CHART_PROGECT: tebaly/varnish-chart
  CHART_REGISTRY_URL: $CI_REGISTRY/$CHART_PROGECT/$CHART_NAME:$CI_COMMIT_TAG

stages:
  - build
  - deploy
build:
  stage: build
  script:
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - helm chart save $CHART_PATH $CHART_REGISTRY_URL
    - helm chart push $CHART_REGISTRY_URL
  only:
    - tags
  except:
    - pipelines

deploy:
  environment:
    name: development
  stage: deploy
  variables:
    LOCAL_CHART_PATH: /tmp/$CHART_NAME
  script:
    - echo $CHART_REGISTRY_URL
    - echo "$CHART_NAME --- ${LOCAL_CHART_PATH}"
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - helm chart pull $CHART_REGISTRY_URL
    - helm chart export $CHART_REGISTRY_URL -d $CHART_PATHCHART_PATH
    - helm upgrade --install $CHART_NAME ${CHART_PATHCHART_PATH}
#  when: manual
  only:
    refs:
      - pipelines
      - tags
  allow_failure: false


