image:
  name: alpine/helm:3.2.1
  entrypoint: ["/bin/sh", "-c"]

variables:
  HELM_EXPERIMENTAL_OCI: 1
  CHART_NAME: varnish-chart
  CHART_PROGECT: tebaly/$CHART_NAME
  CHART_REGISTRY_URL: $CI_REGISTRY/$CHART_PROGECT:$CI_COMMIT_TAG

stages:
  - build-container
  - build-package

container:
  stage: build-container
  script:
    - echo "$CI_REGISTRY_PASSWORD" | helm registry login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - helm chart save ./ $CHART_REGISTRY_URL
    - helm chart push $CHART_REGISTRY_URL
  only:
    - tags

package:
  stage: build-package
  variables:
    PACKAGE_NAME: "varnish"
    PACKAGE_VERSION: "0.6.2"
  script:
    - echo "$CI_REGISTRY_PASSWORD" | helm registry login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - helm package ./
    - apk add git
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm push "${PACKAGE_NAME}-${PACKAGE_VERSION}.tgz" PACKAGE_NAME
  only:
    - tags


