image:
  name: alpine/helm:3.6.2
  entrypoint: ["/bin/sh", "-c"]

variables:
  HELM_EXPERIMENTAL_OCI: 1
  CHART_NAME: varnish
  CHART_APP_VERSION: "6.4"

stages:
  - build-container
#  - build-package
  - build-pages

container:
  stage: build-container
  script:
    - echo "$CI_REGISTRY_PASSWORD" | helm registry login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - echo $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - helm chart save ./ $CI_REGISTRY_IMAGE/$CHART_NAME:$CI_COMMIT_TAG
    - helm chart push $CI_REGISTRY_IMAGE/$CHART_NAME:$CI_COMMIT_TAG
    - helm chart save ./ $CI_REGISTRY_IMAGE/$CHART_NAME:latest
    - helm chart push $CI_REGISTRY_IMAGE/$CHART_NAME:latest
  only:
    - tags

pages:
  image: dtzar/helm-kubectl:3.7.1
  stage: build-pages
  variables:
    HELM_REPO_URL: "https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}"
  before_script:
    - apk add git
    - mkdir -p ./public
    - echo $HELM_REPO_URL
  script:
    - helm package . --version="$CI_COMMIT_TAG" --app-version="$CHART_APP_VERSION"
    - helm repo index ./ --url="$HELM_REPO_URL"
    - mv "varnish-${CI_COMMIT_TAG}.tgz" ./public
    - mv index.yaml ./public
  artifacts:
    paths:
      - public
  only:
    - tags

#package:
#  image: dtzar/helm-kubectl:3.7.1
#  stage: build-package
#  variables:
#    HELM_REPO_URL: "$CI_PROJECT_NAME ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable"
#  before_script:
#    - apk add git
#    - helm plugin install https://github.com/chartmuseum/helm-push.git
#    - echo $HELM_REPO_URL
#    - helm package . --version="$CI_COMMIT_TAG" --app-version="$CHART_APP_VERSION"
#    - helm repo index ./ --url="$HELM_REPO_URL"
#    - helm repo add --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_PROJECT_NAME "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable"
#  script:
#    - helm cm-push ./ $CI_PROJECT_NAME
#  only:
#    - tags


