image:
  name: alpine/helm:3.2.1
  entrypoint: ["/bin/sh", "-c"]

variables:
  HELM_EXPERIMENTAL_OCI: 1
  CHART_NAME: varnish

stages:
  - build-container
  - build-package

container:
  stage: build-container
  script:
    - echo "$CI_REGISTRY_PASSWORD" | helm registry login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - echo $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - helm chart save ./ $CI_REGISTRY_IMAGE/$CHART_NAME:$CI_COMMIT_TAG
    - helm chart push $CI_REGISTRY_IMAGE/$CHART_NAME:$CI_COMMIT_TAG
    - helm chart save ./ $CI_REGISTRY_IMAGE/$CHART_NAME:latest
    - helm chart push $CI_REGISTRY_IMAGE/$CHART_NAME:latest
  only:
    - tags

package:
  image: dtzar/helm-kubectl
  stage: build-package
  before_script:
    - apk add git
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - echo "$CI_PROJECT_NAME ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable"
    - 'helm repo add --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_PROJECT_NAME ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable'
  script:
    - helm cm-push ./ --version="$CI_COMMIT_TAG" $CI_PROJECT_NAME
  only:
    - tags


